# This is a basic workflow to help you get started with Actions

name: otew
# ------------------------------------ #
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# ------------------------------------ #
jobs:
  mniso:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        testi: [mo9x.19, 2ud7, 278, 2v, 9e, 93h, os, yys,]
        flaga: [Aqhmdw, hjjcis, ]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runneyr_go
      run: |
        sudo apt update -y && sleep 7
        
  roart-linux:
    needs: [mniso]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,3.9]
        check: [tesv1,tev2,tckt3,test 4,test5,test6,test7,test8,test9,test10]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Bauo maov .
      run: |
        cd barg
        ls
        pip3 install selenium
        python bavum.py
        
  roart-mac:
    needs: [mniso]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,3.9]
        check: [tehs1,tesmt2,tebst3,tebst4,test5,test6,test7,test8,test9,test10]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: EBromd mao ..
      run: |
        cd barg
        ls
        pip3 install selenium
        python bavum.py
